### PR TITLE
Log exceptions passed to NonBlockingClientAdapter

### LINKED ISSUE #28: Using NonBlockingClientAdapter can conceal error information
If I extend `NonBlockingClientAdapter`, but don't override the default implementations for both the `onRetrying` and `onStopping` methods then I can miss useful exception messages that could help me debug problems with my application.

The default implementations for `onRetrying` and `onStopping` should log any exceptions passed in as arguments - to make it more difficult for someone to miss this information.  Such a change would not affect anyone who already overrides these methods (and presumably is looking at the exceptions being passed in).  Anyone who doesn't override these methods - and doesn't want the exceptions to be logged can trivially override the methods and specify an empty method body.

### PR DESCRIPTION
**Pull request by prestona**
Change the implementation of the onRetrying and onStopping methods to log any
exceptions passed in as arguments. This makes it more difficult for someone who
extends NonBlockingClientAdapter (but doesn't override these methods) to miss
useful debugging information.

This closes #28.

### CODE REVIEW

File: mqlight/src/main/java/com/ibm/mqlight/api/NonBlockingClientAdapter.java [hunk 1]
```diff
@@ -18,27 +18,41 @@
...
  * This class exists as convenience for creating client listener objects.  Extend this class to
- * create a <code>NonBlockingClientListener</code> object and override the methods for the events of interest. 
+ * create a <code>NonBlockingClientListener</code> object and override the methods for the events of interest.
  * (If you implement the <code>NonBlockingClientListener</code> interface, you have to define all of the methods in it.
  * This abstract class defines null methods for them all, so you can only have to define methods for
  * events you care about.)
  */
 public abstract class NonBlockingClientAdapter<T> implements NonBlockingClientListener<T> {
 
+    private static final Logger logger = LoggerFactory.getLogger(NonBlockingClientImpl.class);
```
Comment (dnwe) [inline mqlight/src/main/java/com/ibm/mqlight/api/NonBlockingClientAdapter.java]: @prestona did you intentionally mean to use NonBlockingClientImpl for the logger name rather than NonBlockingClientAdapter?

Comment (prestona) [inline mqlight/src/main/java/com/ibm/mqlight/api/NonBlockingClientAdapter.java]: @dnwe oops.  You can probably guess which class I copied the Logger line from :grinning:.  I'll fix.
